# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RGBIndexCalculator
                                 A QGIS plugin
 This plugin is used for calculaitng image (raster) index values based on RGB images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-11
        copyright            : (C) 2025 by Emir Memic
        email                : emir_memic@windowslive.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RGBIndexCalculator class from file RGBIndexCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rgb_index_calculator import RGBIndexCalculator
    return RGBIndexCalculator(iface)
