# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NDVIandEVIindexCalculator
                                 A QGIS plugin
 This plugin calculates NDVI and EVI index from Sentinel 2 B02, B04 and B08 Bands.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-25
        copyright            : (C) 2024 by Emir Memic
        email                : emir_memic@windowslive.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NDVIandEVIindexCalculator class from file NDVIandEVIindexCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ndvi_and_evi_index_calculator import NDVIandEVIindexCalculator
    return NDVIandEVIindexCalculator(iface)
